<?php
    class Countries{
        public $eu = array(
            'Austria',
            'Belgium',
            'Czech Republic',
            'Denmark',
            'Dstonia',
            'Finland',
            'France',
            'Germany',
            'Greece',
            'Hungary',
            'Iceland',
            'Italy',
            'Latvia',
            'Liechtenstein',
            'Lithuania',
            'Luxemberg',
            'Malta',
            'Netherlands',
            'Poland',
            'Portugal',
            'Slovakia',
            'Slovenia',
            'Spain',
            'Sweden',        
            'Switzerland',
        );
        public $normal = array(
            'Afghanistan',
            'Albania',
            'Algeria',
            'American Sam',
            'Andorra',
            'Angola',
            'Anguilla',
            'Antigua And Barbuda',
            'Argentina',
            'Armenia',
            'Aruba',
            'Australia',
            'Azerbaijan',
            'Bahamas',
            'Bahrain',
            'Banladesh',
            'Barbados',
            'Belarus',
            'Belize',
            'Benin',
            'Bermuda',
            'Bhutan',
            'Bolivia',
            'Bosnia',
            'Botswana',
            'Brazil',
            'Brunie Daruss.',
            'Bulgaria',
            'Burkina Faso',
            'Burundi',
            'Cambodia',
            'Cameroon',
            'Canada',
            'Cape Verde',
            'Camayan Islands',
            'Central African Republic',
            'Chad',
            'Channel Islands',
            'Chile',
            'China',
            'Christmas Islands',
            'Cocos Keeling Isl',
            'Colombia',
            'Comoros',
            'Congo',
            'Cook Islands',
            'Costa Rica',
            'Croatia',
            'Cuba',
            'Cyprus',
            'Czechia',
            'Djibouti',
            'Dominica',
            'Dominican Republic',
            'East Timor',
            'Ecuador',
            'Egypt',
            'El Salvador',
            'Equatorial Guin',
            'Eritrea',
            'Ethiopia',
            'Falkand Islands',
            'Faroe Islands',
            'Fiji',
            'French Polynesia',
            'French Southern Ter',
            'Gabon',
            'Gambia',
            'Georgia',
            'Ghana',
            'Gibraltar',
            'Greenland',
            'Grenada',
            'Guadeloupe',
            'Guam',
            'Guatemala',
            'Guinea',
            'Guinea Bissau',
            'Guyana',
            'Haiti',
            'Honduras',
            'Hong Kong',
            'India',
            'Indonesia',
            'Iran',
            'Iraq',
            'Ireland',
            'Israel',
            'Israel',
            'Ivory Coast',
            'Jamaica',
            'Japan',
            'Jordan',
            'Kazakhstan',
            'Kenya',
            'Kiribati',
            'Kosovo',
            'Kuwait',
            'Krygyzstan',
            'Laos',
            'Lebanon',
            'Lesotho',
            'Liberia',
            'Libyan Arab Jamahiriya',
            'Macau',
            'Macedonia',
            'Madagascar',
            'Malawi',
            'Malaysia',
            'Maldives', 
            'Mali',
            'Marshall Islands',
            'Martinique',
            'Mauritanina',
            'Mauritius',
            'Mayotte',
            'Mexico',
            'Micronesia',
            'Moldova',
            'Monaco',
            'Mongolia',
            'Montenegro',
            'Montserrat',
            'Morocco',
            'Mozambique',
            'Myanmar',
            'Namibia',
            'Nauro',
            'Nepal',
            'Netherlands Antilles',
            'New Caledonina',
            'New Zealand',
            'Nicaragua',
            'Niger',
            'Nigeria',
            'Niue',
            'Norfolk Island',
            'Northern Mariana Isl',
            'Norway',
            'Oman',
            'Pakistan',
            'Palau',
            'Palestine',
            'Panama',
            'Papua New Guinea',
            'Paraguay',
            'Peru',
            'Philippines',
            'Pitcairn',
            'Puerto Rico',
            'Qatar',
            'Reunion',
            'Romania',
            'Russian Federation',
            'Rwanda',
            'Saint Barthelemy',
            'Saint Lucia',
            'Saint Vincent And The Grenadines',
            'Samoa',
            'San Marino',
            'Saudi Arabia',
            'Scotland',
            'Senegal',
            'Serbia',
            'Seychelles',
            'Sierra Leone',
            'Singapore',
            'Solomon Islands',
            'Somalia',
            'South Africa',
            'South Korea',
            'Sri Lanka',
            'Sthelina',
            'Sudan',
            'Suriname',
            'Swaziland',
            'Syrian Arab Republic',
            'São Tomé And Príncipe',
            'Taiwan',
            'Tajikistan',
            'Tanzania',
            'Thailand',
            'Togo',
            'Tokelau',
            'Tonga',
            'Trinidad And Tobago',
            'Tunisia',
            'Turkey',
            'Turkmenistan',
            'Tuvalu',
            'USA',
            'US Minor Outlying Isl',
            'Uganda',
            'Ukraine',
            'United Arab Emirates',
            'United Kingdom',
            'Uruguay',
            'Uzbekistan',
            'Vanuatu',
            'Vatican City St.',
            'Wallis Futuna Islands',
            'Western Sahara',
            'Yemen',
            'Zaire',
            'Zambia',
            'Zimbabwe'
        );
}
?>